### ISSUE TITLE
Drag and Drop doesn't work with DraggableViewCell

### ISSUE THREAD

**Issue by champcbg** [roubachof/Sharpnado.Presentation.Forms#108] opened 2020-04-23 16:10 UTC
**Platform (please complete the following information):**
 - OS: [Android]
 - Device: [Pixel/AndroidEmulator/...]
 - Sdk vervion: [Android SDK 29]
 - Xamarin.Forms: [4.5.0.530]

**Describe the bug**
I am attempting to drag and drop in the gridview and trigger never fires (is my assumption as i type).  The element never gets picked up to be dragged.

```
            <StackLayout  Grid.Row="1">
                <!--Margin="{core:OnPlatformOrientationThickness PhonePortrait='20,32',
                PhoneLandscape='150,32',
                TabletPortrait='200,50',
                TabletLandscape='300,50',
                Desktop='30'}"-->
                <renderedViews:HorizontalListView CollectionPadding="16"
                                  ItemSpacing="0"
                                  EnableDragAndDrop="True"
                                  ItemWidth="110"
                                  ItemHeight="120"
                                  ItemsSource="{Binding Images}"
                                  ListLayout="Grid">
                    <!---->
                    <renderedViews:HorizontalListView.ItemTemplate>
                        <DataTemplate>
                            <renderedViews:DraggableViewCell x:Name="DraggableViewCell">
                                <ContentView>
                                    <renderedViews:MaterialFrame Margin="4"
                                                 
                                                 Elevation="4"><!--Padding="{StaticResource StandardThickness}"-->

                                        <Frame.Triggers>
                                            <DataTrigger Binding="{Binding Source={x:Reference DraggableViewCell}, Path=IsDragAndDropping}"
                                         TargetType="renderedViews:MaterialFrame"
                                         Value="True">
                                                <Setter Property="Elevation" Value="8" />
                                            </DataTrigger>
                                        </Frame.Triggers>

                                        <Image Source="{Binding AppPrivatePath}"
                                               Aspect="AspectFill"
                                               HeightRequest="120"
                                               WidthRequest="110"
                                              /> 
                                        <!---->

                                       
                                    </renderedViews:MaterialFrame>
                                </ContentView>
                            </renderedViews:DraggableViewCell>
                        </DataTemplate>
                    </renderedViews:HorizontalListView.ItemTemplate>
                </renderedViews:HorizontalListView>
            </StackLayout>
```

**To Reproduce**
1. click and hold mouse on image ... or press with finger and hold 
2. attempt to drag
3. nothing happens

**Exceptions (if applicable)**
Copy paste the exception and the stack trace
```
Unhandled Exception:
System.InvalidOperationException: exception message
  at Namespace.Call
  at ....
```

**Screenshots (if applicable)**
![image](https://user-images.githubusercontent.com/4595766/80122271-53a40e00-855b-11ea-9b7d-9e31bde57a67.png)

**Comment by ske66** [comment] 2020-04-23 17:31
I had the same issue. The docs is a bit scattered and the solution is in the Silly app project. Inside your DraggableViewCell you need to include the IsDraggable property and set it to true.

**Comment by roubachof** [comment] 2020-04-23 18:58
The docs are here:

https://github.com/roubachof/Sharpnado.Presentation.Forms/wiki

And the sample app is here:

https://github.com/roubachof/Xamarin-Forms-Practices

> Inside your DraggableViewCell you need to include the IsDraggable property and set it to true.

Thank you for pointing this out, it's a regression, default should be true.

Also: you don't have to use DraggableViewCell, you can use any ViewCell.

**Comment by roubachof** [comment] 2020-04-24 00:04
@champcbg did you understand the issue?
Either don't use a DraggableViewCell, or set the IsDraggable property of the DraggableViewCell to true.

**Comment by champcbg** [comment] 2020-04-24 00:09
Thanks i did not realize there was that distinction.

I have been trying it and the drag and drop was not happening.  I was doing this and not still not getting the drag and drop.  So going to try that with the standard ViewCell

```
                 <renderedViews:DraggableViewCell x:Name="DraggableViewCell"
                                                             IsDraggable="True">
```

**Comment by champcbg** [comment] 2020-04-24 00:17
I also tried this way and still no drag or drop
```

 <renderedViews:HorizontalListView CollectionPadding="16"
                                  ItemSpacing="0"
                                  EnableDragAndDrop="True"
                                  ItemWidth="110"
                                  ItemHeight="120"
                                  ItemsSource="{Binding Images}"
                                  ListLayout="Grid">
                    <!---->
                    <renderedViews:HorizontalListView.ItemTemplate>
                        <DataTemplate>
                            <ViewCell x:Name="DraggableViewCell">
                                <ContentView>
                                    <renderedViews:MaterialFrame Margin="4"
                                                 
                                                 Elevation="4">

                                        <Frame.Triggers>
                                            <DataTrigger Binding="{Binding Source={x:Reference DraggableViewCell}, Path=IsDragAndDropping}"
                                         TargetType="renderedViews:MaterialFrame"
                                         Value="True">
                                                <Setter Property="Elevation" Value="8" />
                                            </DataTrigger>
                                        </Frame.Triggers>

                                        <Image Source="{Binding AppPrivatePath}"
                                               Aspect="AspectFill"
                                               HeightRequest="120"
                                               WidthRequest="110"
                                              /> 
                                        <!---->

                                       
                                    </renderedViews:MaterialFrame>
                                </ContentView>
                            </ViewCell>
                        </DataTemplate>
                    </renderedViews:HorizontalListView.ItemTemplate>
                </renderedViews:HorizontalListView>
```

**Comment by roubachof** [comment] 2020-04-24 09:15
well it's weird cause it's working for everyone else...
I will need a full repro sample to see what's going on.

**Comment by champcbg** [comment] 2020-04-24 16:06
> well it's weird cause it's working for everyone else...
> I will need a full repro sample to see what's going on.

LOL... Story of my life, im always the odd man out.  Let me try putting together a simple repo if that works i know its something in my app specifically causing the issue

**Comment by roubachof** [comment] 2020-05-20 15:16
Gonna close this since it's been about a month now.

**Closed by roubachof** 2020-05-20 15:16 UTC
