### ISSUE TITLE
How to swipe between tabs

### ISSUE THREAD

**Issue by naaeef** [roubachof/Sharpnado.Presentation.Forms#78] opened 2019-08-14 09:45 UTC
Is it possible to swipe between the different tabs when using UnderlinedTabItem? If yes, how do I enable it?

**Comment by roubachof** [comment] 2019-08-14 10:29
duplicate of https://github.com/roubachof/Sharpnado.Presentation.Forms/issues/68

**Closed** 2019-08-14 10:32 UTC
Labels: duplicate, question
