### ISSUE TITLE
HorizontalListView not shown after updating ItemsSource

### ISSUE THREAD

**Issue by mr5z** [roubachof/Sharpnado.Presentation.Forms#20] opened 2019-01-28 04:34 UTC
**Platform:**
 - OS: Android
 - Device: Samsung S7 Edge

**Describe the bug**
Please take a look [at this line](https://github.com/roubachof/Sharpnado.Presentation.Forms/blob/master/Sharpnado.Presentation.Forms.Droid/Renderers/HorizontalList/AndroidHorizontalListViewRenderer.cs#L285). It should reuse that adapter instead of creating new one every ItemsSource update.

**To Reproduce**
Just copy-pasted some of the examples here. Nothing fancy about my implementation.

**Exceptions (if applicable)**
NA

**Screenshots (if applicable)**
NA

**Comment by roubachof** [comment] 2019-01-28 10:44
Sorry to disagree but it's pretty common to reset the adapter when you change your items source.

I tried to replicate your issue with no luck.
I added a ```ChangeItemsSource``` method in my ```SillyInfinitePeopleVm```:

```csharp
        private async Task<PageResult<SillyDude>> LoadSillyPeoplePageAsync(int pageNumber, int pageSize)
        {
            PageResult<SillyDude> resultPage = await _sillyDudeService.GetSillyPeoplePage(pageNumber, pageSize);
            var viewModels = resultPage.Items.Select(dude => new SillyDudeVmo(dude, GoToSillyDudeCommand)).ToList();
            SillyPeople.AddRange(viewModels);

            // Uncomment to test CurrentIndex property
            NotifyTask.Create(
               async () =>
               {
                   await Task.Delay(2000);
                   CurrentIndex = 5;

                   await ChangeItemsSource();
               });

            return resultPage;
        }

        private async Task ChangeItemsSource()
        {
            await Task.Delay(4000);

            PageResult<SillyDude> resultPage = await _sillyDudeService.GetSillyPeoplePage(1, 20);
            var viewModels = resultPage.Items.Select(dude => new SillyDudeVmo(dude, GoToSillyDudeCommand)).ToList();
            SillyPeople = new ObservableRangeCollection<SillyDudeVmo>(viewModels);
            Debug.WriteLine("Raising property changed for SillyPeople ItemsSource");
            RaisePropertyChanged(nameof(SillyPeople));
        }
```

The ```ItemsSource``` is updated and the list is shown without any issue.

**Comment by roubachof** [comment] 2019-02-11 08:03
closed this since it's been 2 weeks.

**Closed by roubachof** 2019-02-11 08:03 UTC
Labels: not reproducible

**Comment by muhammetsahin** [comment] 2019-02-15 12:21
Hi, I have same issue.

Here is some screenshots:
![image](https://user-images.githubusercontent.com/2045788/52856343-32fd4e80-3135-11e9-9abb-a64b1f94d3c8.png)

Use prism forms mvvm
![image](https://user-images.githubusercontent.com/2045788/52856359-3d1f4d00-3135-11e9-8f9a-d3cd4f30b5c8.png)


![image](https://user-images.githubusercontent.com/2045788/52856383-4e685980-3135-11e9-80f6-7893c1a0b908.png)

But nothing show

![image](https://user-images.githubusercontent.com/2045788/52856399-57f1c180-3135-11e9-8394-4312073c6bd1.png)

@roubachof 

Thanks.

**Comment by roubachof** [comment] 2019-02-16 11:25
As I said before, I cannot reproduce. If you send me a repro solution I will investigate it!

**Comment by muhammetsahin** [comment] 2019-02-17 17:01
Hi @roubachof  i added our repo.. Could you please look?

Thanks.
