### ISSUE TITLE
ScrollEndedCommand does not fire

### ISSUE THREAD

**Issue by DottorPagliaccius** [roubachof/Sharpnado.Presentation.Forms#7] opened 2018-11-09 10:50 UTC
**Platform (please complete the following information):**
 - OS: [Both]
 - Device: [All]

**Describe the bug**
ScrollEndedCommand does not fire. I searched the code and find out that the command is never invoked.

https://github.com/roubachof/Sharpnado.Presentation.Forms/search?q=ScrollEndedCommand&unscoped_q=ScrollEndedCommand

Apart from this, the control is great, thank you ;)

**Comment by roubachof** [comment] 2018-11-09 11:57
Argh! This is an ugly regression, I remember than disabling it monthes ago... Should have test the damn thing!
Well this in infortunate since I'm on vacation in japan, and I will get back only 1st december.
But I promise you I will fix at when I return.

**Comment by roubachof** [comment] 2018-12-17 17:42
fixed in 0.9.7

**Closed by roubachof** 2018-12-17 17:42 UTC
Labels: bug
