### ISSUE TITLE
System.ObjectDisposedException: Cannot access a disposed object.

### ISSUE THREAD

**Issue by OKameric** [roubachof/Sharpnado.Presentation.Forms#73] opened 2019-07-26 08:31 UTC
**Platform:**

- OS: Android
- Device: Pixel 2 XL
- Sdk vervion: Android SDK 28
- Xamarin.Forms: 4.0.0.497661
- Sharpnado.Presentation.Forms: 1.2.0

**Describe the bug**
When I use an image with FontImageSource as the source I get the following exception when I come back to the page where the horizontal list is present (with regular ImageSource it works):

**Exceptions:**

System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Xamarin.Forms.Platform.Android.FastRenderers.ImageRenderer'.

07-26 10:18:39.141 D/Mono    (20649): DllImport attempting to load: '/system/lib64/liblog.so'.
07-26 10:18:39.143 D/Mono    (20649): DllImport loaded library '/system/lib64/liblog.so'.
07-26 10:18:39.143 D/Mono    (20649): DllImport searching in: '/system/lib64/liblog.so' ('/system/lib64/liblog.so').
07-26 10:18:39.143 D/Mono    (20649): Searching for '__android_log_print'.
07-26 10:18:39.143 D/Mono    (20649): Probing '__android_log_print'.
07-26 10:18:39.143 D/Mono    (20649): Found as '__android_log_print'.
07-26 10:18:39.153 I/MonoDroid(20649): UNHANDLED EXCEPTION:
07-26 10:18:39.157 I/MonoDroid(20649): System.ObjectDisposedException: Cannot access a disposed object.
07-26 10:18:39.157 I/MonoDroid(20649): Object name: 'Xamarin.Forms.Platform.Android.FastRenderers.ImageRenderer'.
07-26 10:18:39.157 I/MonoDroid(20649):   at Java.Interop.JniPeerMembers.AssertSelf (Java.Interop.IJavaPeerable self) [0x00029] in <3beddfcb1eb547cd8ce47c3097f6eaeb>:0 
07-26 10:18:39.157 I/MonoDroid(20649):   at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualInt32Method (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x00000] in <3beddfcb1eb547cd8ce47c3097f6eaeb>:0 
07-26 10:18:39.157 I/MonoDroid(20649):   at Android.Views.View.get_Visibility () [0x0000a] in <ff9f3f3d4e134974a889db1b532c9b6e>:0 
07-26 10:18:39.157 I/MonoDroid(20649):   at Xamarin.Forms.Platform.Android.VisualElementTracker.UpdateIsVisible () [0x0002e] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementTracker.cs:329 
07-26 10:18:39.157 I/MonoDroid(20649):   at Xamarin.Forms.Platform.Android.VisualElementTracker.HandlePropertyChanged (System.Object sender, System.ComponentModel.PropertyChangedEventArgs e) [0x00347] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementTracker.cs:169 
07-26 10:18:39.157 I/MonoDroid(20649):   at (wrapper delegate-invoke) <Module>.invoke_void_object_PropertyChangedEventArgs(object,System.ComponentModel.PropertyChangedEventArgs)
07-26 10:18:39.157 I/MonoDroid(20649):   at Xamarin.Forms.BindableObject.OnPropertyChanged (System.String propertyName) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:211 
07-26 10:18:39.157 I/MonoDroid(20649):   at Xamarin.Forms.Element.OnPropertyChanged (System.String propertyName) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\Element.cs:353 
07-26 10:18:39.157 I/MonoDroid(20649):   at Xamarin.Forms.BindableObject.SetValueActual (Xamarin.Forms.BindableProperty property, Xamarin.Forms.BindableObject+BindablePropertyContext context, System.Object value, System.Boolean currentlyApplying, Xamarin.Forms.Internals.SetValueFlags attributes, System.Boolean silent) [0x00114] in D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:443 
07-26 10:18:39.157 I/MonoDroid(20649):   at Xamarin.Forms.BindableObject.SetValueCore (Xamarin.Forms.BindableProperty property, System.Object value, Xamarin.Forms.Internals.SetValueFlags attributes, Xamarin.Forms.BindableObject+SetValuePrivateFlags privateAttributes) [0x00173] in D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:379 
07-26 10:18:39.157 I/MonoDroid(20649):   at Xamarin.Forms.BindingExpression.ApplyCore (System.Object sourceObject, Xamarin.Forms.BindableObject target, Xamarin.Forms.BindableProperty property, System.Boolean fromTarget) [0x00220] in D:\a\1\s\Xamarin.Forms.Core\BindingExpression.cs:167 
07-26 10:18:39.157 I/MonoDroid(20649):   at Xamarin.Forms.BindingExpression.Apply (System.Boolean fromTarget) [0x0003e] in D:\a\1\s\Xamarin.Forms.Core\BindingExpression.cs:57 
07-26 10:18:39.157 I/MonoDroid(20649):   at Xamarin.Forms.BindingExpression+BindingExpressionPart.<PropertyChanged>b__49_0 () [0x00000] in D:\a\1\s\Xamarin.Forms.Core\BindingExpression.cs:618 
07-26 10:18:39.157 I/MonoDroid(20649):   at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <ff9f3f3d4e134974a889db1b532c9b6e>:0 
07-26 10:18:39.157 I/MonoDroid(20649):   at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00009] in <ff9f3f3d4e134974a889db1b532c9b6e>:0 
07-26 10:18:39.157 I/MonoDroid(20649):   at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.44(intptr,intptr)
07-26 10:18:39.167 E/AppCenterCrashes(20649): Unhandled Exception from source=AndroidEnvironment
07-26 10:18:39.167 E/AppCenterCrashes(20649): System.ObjectDisposedException: Cannot access a disposed object.
07-26 10:18:39.167 E/AppCenterCrashes(20649): Object name: 'Xamarin.Forms.Platform.Android.FastRenderers.ImageRenderer'.
07-26 10:18:39.167 E/AppCenterCrashes(20649):   at Java.Interop.JniPeerMembers.AssertSelf (Java.Interop.IJavaPeerable self) [0x00029] in <3beddfcb1eb547cd8ce47c3097f6eaeb>:0 
07-26 10:18:39.167 E/AppCenterCrashes(20649):   at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualInt32Method (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x00000] in <3beddfcb1eb547cd8ce47c3097f6eaeb>:0 
07-26 10:18:39.167 E/AppCenterCrashes(20649):   at Android.Views.View.get_Visibility () [0x0000a] in <ff9f3f3d4e134974a889db1b532c9b6e>:0 
07-26 10:18:39.167 E/AppCenterCrashes(20649):   at Xamarin.Forms.Platform.Android.VisualElementTracker.UpdateIsVisible () [0x0002e] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementTracker.cs:329 
07-26 10:18:39.167 E/AppCenterCrashes(20649):   at Xamarin.Forms.Platform.Android.VisualElementTracker.HandlePropertyChanged (System.Object sender, System.ComponentModel.PropertyChangedEventArgs e) [0x00347] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementTracker.cs:169 
07-26 10:18:39.167 E/AppCenterCrashes(20649):   at (wrapper delegate-invoke) <Module>.invoke_void_object_PropertyChangedEventArgs(object,System.ComponentModel.PropertyChangedEventArgs)
07-26 10:18:39.167 E/AppCenterCrashes(20649):   at Xamarin.Forms.BindableObject.OnPropertyChanged (System.String propertyName) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:211 
07-26 10:18:39.167 E/AppCenterCrashes(20649):   at Xamarin.Forms.Element.OnPropertyChanged (System.String propertyName) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\Element.cs:353 
07-26 10:18:39.167 E/AppCenterCrashes(20649):   at Xamarin.Forms.BindableObject.SetValueActual (Xamarin.Forms.BindableProperty property, Xamarin.Forms.BindableObject+BindablePropertyContext context, System.Object value, System.Boolean currentlyApplying, Xamarin.Forms.Internals.SetValueFlags attributes, System.Boolean silent) [0x00114] in D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:443 
07-26 10:18:39.167 E/AppCenterCrashes(20649):   at Xamarin.Forms.BindableObject.SetValueCore (Xamarin.Forms.BindableProperty property, System.Object value, Xamarin.Forms.Internals.SetValueFlags attributes, Xamarin.Forms.BindableObject+SetValuePrivateFlags privateAttributes) [0x00173] in D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:379 
07-26 10:18:39.167 E/AppCenterCrashes(20649):   at Xamarin.Forms.BindingExpression.ApplyCore (System.Object sourceObject, Xamarin.Forms.BindableObject target, Xamarin.Forms.BindableProperty property, System.Boolean fromTarget) [0x00220] in D:\a\1\s\Xamarin.Forms.Core\BindingExpression.cs:167 
07-26 10:18:39.167 E/AppCenterCrashes(20649):   at Xamarin.Forms.BindingExpression.Apply (System.Boolean fromTarget) [0x0003e] in D:\a\1\s\Xamarin.Forms.Core\BindingExpression.cs:57 
07-26 10:18:39.167 E/AppCenterCrashes(20649):   at Xamarin.Forms.BindingExpression+BindingExpressionPart.<PropertyChanged>b__49_0 () [0x00000] in D:\a\1\s\Xamarin.Forms.Core\BindingExpression.cs:618 
07-26 10:18:39.167 E/AppCenterCrashes(20649):   at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <ff9f3f3d4e134974a889db1b532c9b6e>:0 
07-26 10:18:39.167 E/AppCenterCrashes(20649):   at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00009] in <ff9f3f3d4e134974a889db1b532c9b6e>:0 
07-26 10:18:39.167 E/AppCenterCrashes(20649):   at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.44(intptr,intptr)
07-26 10:18:39.180 D/Mono    (20649): Assembly Ref addref Microsoft.AppCenter.Crashes[0x6fd8c23200] -> System.Core[0x6fd7314e00]: 20
07-26 10:18:39.315 W/com.comeco.teo(20649): JNI RegisterNativeMethods: attempt to register 0 native methods for android.runtime.JavaProxyThrowable
07-26 10:18:39.317 D/Mono    (20649): DllImport searching in: '__Internal' ('(null)').
07-26 10:18:39.317 D/Mono    (20649): Searching for 'java_interop_jnienv_throw'.
07-26 10:18:39.317 D/Mono    (20649): Probing 'java_interop_jnienv_throw'.
07-26 10:18:39.317 D/Mono    (20649): Found as 'java_interop_jnienv_throw'.
Unhandled Exception:

System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Xamarin.Forms.Platform.Android.FastRenderers.ImageRenderer'.

07-26 10:18:40.244 E/mono-rt (20649): [ERROR] FATAL UNHANDLED EXCEPTION: System.ObjectDisposedException: Cannot access a disposed object.
07-26 10:18:40.244 E/mono-rt (20649): Object name: 'Xamarin.Forms.Platform.Android.FastRenderers.ImageRenderer'.
07-26 10:18:40.244 E/mono-rt (20649):   at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.44(intptr,intptr)
07-26 10:18:40.244 E/mono-rt (20649):   at (wrapper native-to-managed) Android.Runtime.DynamicMethodNameCounter.44(intptr,intptr)

Thanks for an awesome library!

**Comment by roubachof** [comment] 2019-07-26 09:10
Thanks for the kind word :)
As you can see in the exception stack, it seems that it has nothing to do with the horizontal list view :(

**Comment by brakonier946** [comment] 2019-07-26 10:42
> Thanks for the kind word :)
> As you can see in the exception stack, it seems that it has nothing to do with the horizontal list view :(

Hello.
I have this bug when set BindingContext to null and set again.
I download your project and include in my project.
When I walked through the steps I had seen that you dispose previous RecyclerViewAdapter but into him come event about collection is changed even though you should check on the dispose.
I add this check in methods which you add/remove items and notify recycler view and does not have this error again

**Comment by roubachof** [comment] 2019-07-26 10:44
Cool if you found the bug! Could you make a PR? Would be happy to merge it :)

**Comment by brakonier946** [comment] 2019-07-26 12:17
Okay
You can open for me repository?

**Comment by roubachof** [comment] 2019-07-26 12:22
You have to clone the repo, then make the modifications, and then create a pull request:

https://help.github.com/en/articles/creating-a-pull-request-from-a-fork

**Comment by roubachof** [comment] 2019-08-27 20:45
duplicate of #72

**Closed by roubachof** 2019-08-27 20:45 UTC
Labels: android, bug, duplicate
