### ISSUE TITLE
Sliding tabs

### ISSUE THREAD

**Issue by nielsenko** [roubachof/Sharpnado.Presentation.Forms#82] opened 2019-09-10 08:31 UTC
I would like ViewSwitcher to be able to slide between views.  Just an idea :-)

**Comment by roubachof** [comment] 2019-09-10 09:29
duplicate of #68 and #78 :)

**Comment by nielsenko** [comment] 2019-09-10 10:40
😊 Sorry, I should have checked existing issues.

**Closed** 2019-09-10 11:07 UTC
Labels: duplicate, question
