### ISSUE TITLE
Dynamic height allocation for views in HorizontalListView

### ISSUE THREAD

**Issue by PouyaJavadzadeh** [roubachof/Sharpnado.Presentation.Forms#10] opened 2018-11-19 21:25 UTC
**Is your feature request related to a problem? Please describe.**
At the moment, size allocation for the items in a HorizontalLisView is not dynamic and the size shall be explicitly specified. This is particularly troublesome when ItemHeight is allocated at runtime.

**Describe the solution you'd like**
It would be useful if the Element.HeightRequest changes based on the content size in scenarios that ItemHeight is not pre-determined.

**Describe alternatives you've considered**
Creating a converter to calculate the ItemHeight at runtime.

**Comment by roubachof** [comment] 2018-11-20 14:14
It’s indeed something on the roadmap.

**Comment by LeoJHarris** [comment] 2018-11-20 21:57
Up voting this request. I would consider this a must on this component.

**Comment by roubachof** [comment] 2018-12-17 10:33
I've given some thoughts on the subject and updating the control ```HeightRequest``` based on the ```ItemHeight``` seems to be a bad design choice in my opinion.

This is a horizontal list and by design, you need to have a fixed height for this type of component.
Consider a basic list view (vertical): you alsways specify the width of it, you wouldn't want the width of the list to change based on the item content width.

The only thing that could make sense is to have a dynamic ```ItemWidth``` based on the number of items we want to display. For example we would like only one item displayed taking all the parent width and we would achieve a ```CarouselView``` behavior.

Maybe I didn't completly understood your needs. In this case it would be helpful to give me a concrete example.

**Comment by roubachof** [comment] 2019-01-08 13:19
checkout v0.9.8 release, some auto computation could please you :)

**Comment by roubachof** [comment] 2019-01-27 17:04
@PouyaJavadzadeh @LeoJHarris, I will close this with your permission.

**Comment by moreirawebmaster** [comment] 2019-01-28 03:00
407/5000
I have the scenario, I need to tapped on the line and it automatically expand.

Today I have the List with 1 Grid EnableDragAndDrop column and to tapped on the child it will load another content, and in that child will display some data.

Unfortunately, the listing needs FIXED (ItemHeight) and this makes it difficult because the children on the list have the flexibility to automatically increase their height.

**Comment by roubachof** [comment] 2019-01-28 08:46
hi @moreirawebmaster !

I'm afraid for now I won't support dynamic sizing as it induces too much complexity :(

**Closed** 2019-02-03 16:03 UTC
Labels: enhancement

**Comment by iamlawrencev** [comment] 2020-04-17 05:22
Hi @roubachof. First of all thank you for your amazing plugin. I have a question, is there support for dynamic width that is dependent on the element size? I have a horizontal list where the views are labels that have different lengths.
